# Generated by Django 5.0 on 2023-12-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_app', '0002_nota_aprovado_nota_media_nota_nota_artes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='nota_artes',
            new_name='nota1_artes',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='nota_ciencias',
            new_name='nota1_ciencias',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='nota_geografia',
            new_name='nota1_geografia',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='nota_historia',
            new_name='nota1_historia',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='nota_ingles',
            new_name='nota1_ingles',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='nota_matematica',
            new_name='nota1_matematica',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='nota_portugues',
            new_name='nota1_portugues',
        ),
        migrations.AddField(
            model_name='nota',
            name='nota2_artes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota2_ciencias',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota2_geografia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota2_historia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota2_ingles',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota2_matematica',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota2_portugues',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota3_artes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota3_ciencias',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota3_geografia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota3_historia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota3_ingles',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota3_matematica',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota3_portugues',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='nota',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
